### PR TITLE
Add multi-arch support (amd64 and arm64)

### PR DESCRIPTION
**Pull request by shumonsharif**

### CODE REVIEW

**Comment by shumonsharif** [comment]
Please hold off merging this, trying to see if I can speed it up a bit more ...

**Comment by shumonsharif** [comment]
Hi @ppalaga I just made some minor tweaks, startup time on my laptop for the container is approx 2 seconds now, as opposed to approx 10 seconds.  Please feel free to let me know in case you have any feedback!

**Comment by ppalaga** [comment]
Great work, thanks @shumonsharif !

**Review by ppalaga — APPROVED** [review]

**Comment by ppalaga** [comment]
It is deployed on quay.io now https://github.com/l2x6/calculator-ws/actions/runs/2991250564

**Pull request merged**
